import { chromium } from 'playwright';
import fs from 'node:fs';
const browser=await chromium.launch();
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[]; page.on('pageerror',error=>errors.push(error.message));
await page.goto('http://localhost:3101/concept');
await page.getByRole('heading',{level:1}).waitFor();
await page.mouse.wheel(0,550);
await page.waitForTimeout(700);
const wheelY=await page.evaluate(()=>scrollY);
if(wheelY<500 || wheelY>600) throw new Error(`Momentum scroll failed: ${wheelY}`);
await page.getByRole('navigation',{name:'Main navigation',exact:true}).getByRole('link',{name:'Pricing',exact:true}).click();
await page.waitForTimeout(1800);
const anchorY=await page.locator('#pricing').evaluate(el=>el.getBoundingClientRect().top);
if(anchorY<80 || anchorY>120) throw new Error(`Anchor hidden under header: ${anchorY}`);
await page.getByRole('button',{name:'Play walkthrough',exact:true}).click();
await page.waitForTimeout(6800);
if(await page.getByRole('button',{name:'The sources',exact:false}).getAttribute('aria-pressed')!=='true')throw new Error('Chapter did not advance');
await page.waitForTimeout(13500);
if(await page.getByRole('button',{name:'The result',exact:false}).getAttribute('aria-pressed')!=='true')throw new Error('Final chapter missing');
if(!(await page.getByRole('button',{name:'Play walkthrough',exact:true}).isVisible()))throw new Error('Walkthrough did not stop');
await page.setViewportSize({width:720,height:500});
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
if(overflow)throw new Error('Overflow at equivalent 200% desktop zoom');
await page.emulateMedia({reducedMotion:'reduce'});
await page.reload();
const scrollBehavior=await page.evaluate(()=>getComputedStyle(document.documentElement).scrollBehavior);
if(scrollBehavior!=='auto')throw new Error('Reduced motion leaves smooth anchors enabled');
if(errors.length)throw new Error(errors.join('\n'));
fs.writeFileSync('design-review/motion-checks.json',JSON.stringify({wheelY,anchorY,automaticChapters:'passed',stopsAtEnd:true,zoomOverflow:false,reducedMotionScrollBehavior:scrollBehavior,errors},null,2));
console.log('Momentum, anchors, automatic playback, 200% layout and reduced motion passed');
await browser.close();
