import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PostHogProvider } from "./providers/PostHogProvider";
import { ClientLayout } from "@/components/ClientLayout";
import { LinkedInInsightTag } from "@/components/LinkedInInsightTag";
import { OrganizationSchema, WebAppSchema } from "@/components/JsonLd";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  metadataBase: new URL("https://casedelta.com"),
  title: {
    default: "CaseDelta — The Personal Assistant That Connects All Your Firm's Tools",
    template: "%s | CaseDelta",
  },
  description:
    "The personal assistant that connects all your firm's tools together, so you can manage all of them with a single sentence. Tell Delta what you need. Many tools, hours of work, done in one go. Built for plaintiff firms.",
  keywords: [
    "legal AI",
    "AI for law firms",
    "AI personal assistant for law firms",
    "legal AI Clio integration",
    "plaintiff law firm AI",
    "personal injury AI",
    "medical malpractice AI",
    "mass tort case management AI",
    "employment law AI",
    "horizontal AI for law firms",
  ],
  authors: [{ name: "CaseDelta", url: "https://casedelta.com" }],
  creator: "CaseDelta",
  publisher: "CaseDelta",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: [
      { url: "/favicon-light.png", media: "(prefers-color-scheme: light)" },
      { url: "/favicon-dark.png", media: "(prefers-color-scheme: dark)" },
    ],
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://casedelta.com",
    siteName: "CaseDelta",
    title: "CaseDelta — The Personal Assistant That Connects All Your Firm's Tools",
    description:
      "The personal assistant that connects all your firm's tools together, so you can manage all of them with a single sentence. Tell Delta what you need. Many tools, hours of work, done in one go.",
    // OG image auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "CaseDelta — The Personal Assistant That Connects All Your Firm's Tools",
    description:
      "Tell Delta what you need. Delta runs the work across Clio, Word, Gmail, Drive, and your calendar. One sentence. Many tools.",
    // Twitter image auto-generated by app/opengraph-image.tsx
  },
  alternates: {
    canonical: "https://casedelta.com",
  },
  verification: {
    // Replace with actual Google Search Console verification code
    // google: "your-verification-code",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light" className={inter.variable} suppressHydrationWarning>
      <head>
        <OrganizationSchema />
        <WebAppSchema />
      </head>
      <body>
        <LinkedInInsightTag />
        <PostHogProvider>
          <ClientLayout>{children}</ClientLayout>
        </PostHogProvider>
      </body>
    </html>
  );
}
