import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PostHogProvider } from "./providers/PostHogProvider";
import { ClientLayout } from "@/components/ClientLayout";
import { LinkedInInsightTag } from "@/components/LinkedInInsightTag";
import { MetaPixel } from "@/components/MetaPixel";
import { OrganizationSchema, WebAppSchema } from "@/components/JsonLd";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  metadataBase: new URL("https://casedelta.com"),
  title: {
    default: "CaseDelta: The AI Associate That Knows Your Case",
    template: "%s | CaseDelta",
  },
  description:
    "CaseDelta is an AI associate for litigation firms. Delta connects across your email, calendar, files, and tasks, keeps every matter current, and does the work, with a cited source for every answer. Your client data is never trained on.",
  keywords: [
    "legal AI",
    "AI associate for law firms",
    "AI for law firms",
    "AI personal assistant for law firms",
    "legal AI Clio integration",
    "litigation AI",
    "AI for litigation firms",
    "connected legal AI",
    "AI legal case management assistant",
    "AI medical chronology",
    "AI demand letter",
    "personal injury AI",
    "medical malpractice AI",
    "insurance defense AI",
    "commercial litigation AI",
    "EvenUp alternative",
    "secure legal AI for law firms",
  ],
  authors: [{ name: "CaseDelta", url: "https://casedelta.com" }],
  creator: "CaseDelta",
  publisher: "CaseDelta",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: [
      { url: "/favicon-light.png", media: "(prefers-color-scheme: light)" },
      { url: "/favicon-dark.png", media: "(prefers-color-scheme: dark)" },
    ],
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://casedelta.com",
    siteName: "CaseDelta",
    title: "CaseDelta: The AI Associate That Knows Your Case",
    description:
      "An AI associate that knows your case. Delta connects across your email, calendar, files, and tasks, so nothing about any matter falls through the cracks, for anyone on your team. Your client data is never trained on.",
    // OG image auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "CaseDelta: The AI Associate That Knows Your Case",
    description:
      "An AI associate that knows your case. Connected across your email, calendar, files, and tasks, so nothing falls through the cracks, for anyone on your team. Your client data is never trained on.",
    // Twitter image auto-generated by app/opengraph-image.tsx
  },
  alternates: {
    canonical: "https://casedelta.com",
  },
  verification: {
    // Replace with actual Google Search Console verification code
    // google: "your-verification-code",
    other: {
      "facebook-domain-verification": "byly9n4j9lcu98ysjyx7tyqqb4jhg5",
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light" className={inter.variable} suppressHydrationWarning>
      <head>
        <OrganizationSchema />
        <WebAppSchema />
      </head>
      <body>
        <LinkedInInsightTag />
        <MetaPixel />
        <PostHogProvider>
          <ClientLayout>{children}</ClientLayout>
        </PostHogProvider>
      </body>
    </html>
  );
}
